apiVersion : apps/v1
kind: Deployment
metadata:
  name: app01 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01 
    spec:
      containers:
        - name: app01 
          image: registry01xtr.azurecr.io/app:40
          ports:
          - containerPort: 80
