
name: Build Web App

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    build: 
        runs-on: ubuntu-latest
    
        steps:
        - uses: action/checkout@v2

        - name: Docker Build
          run: docker build -t app ./src



